/**
 * PAPI v1.14+ Real Generated Descriptors
 *
 * This file uses descriptors generated by the PAPI CLI.
 * To regenerate descriptors for your project, run these commands:
 *
 * npm install polkadot-api
 * npx papi add polkadot --wsUrl wss://rpc.polkadot.io
 * npx papi add kusama --wsUrl wss://kusama-rpc.polkadot.io
 * npx papi add moonbeam --wsUrl wss://wss.api.moonbeam.network
 * npx papi add bifrost --wsUrl wss://hk.p.bifrost-rpc.liebi.com/ws
 * npx papi add astar --wsUrl wss://rpc.astar.network
 * npx papi
 *
 * KNOWN ISSUE: paseo_asset_hub has fundamental encoding incompatibilities with current PAPI version.
 * Error: "inner[tag] is not a function" occurs during transaction encoding.
 * RECOMMENDATION: Use 'polkadot', 'kusama', or other stable chains for transaction testing.
 * Working chains: polkadot, kusama, moonbeam, bifrost, astar
 */

// Import generated descriptors — only chains that were added via `npx papi add` will exist.
// If a chain hasn't been added, it won't be in the generated bundle.
import * as descriptorExports from "@polkadot-api/descriptors";

// Re-export individual descriptors with safe fallbacks for chains not yet generated
const polkadot = (descriptorExports as any).polkadot;
const kusama = (descriptorExports as any).kusama;
const moonbeam = (descriptorExports as any).moonbeam;
const bifrost = (descriptorExports as any).bifrost;
const astar = (descriptorExports as any).astar;
const paseo_asset_hub = (descriptorExports as any).paseo_asset_hub;
const polkadot_asset_hub = (descriptorExports as any).polkadot_asset_hub;
const polkadot_people = (descriptorExports as any).polkadot_people;
const hydration = (descriptorExports as any).hydration;

// Type-safe mapping of chain keys to descriptors (only includes chains that exist)
const CHAIN_DESCRIPTORS: Record<string, any> = Object.fromEntries(
  Object.entries({
    polkadot,
    kusama,
    moonbeam,
    bifrost,
    astar,
    paseo_asset_hub,
    polkadot_asset_hub,
    polkadot_people,
    hydration,
  }).filter(([, v]) => v !== undefined)
);

type SupportedChainKey = keyof typeof CHAIN_DESCRIPTORS;

/**
 * Get the proper descriptor for a chain to use with client.getTypedApi()
 * @param chainKey - The chain identifier
 * @returns The chain descriptor for use with PAPI v1.14+ getTypedApi()
 */
export function getDescriptorForChain(chainKey: string): any {
  const key = chainKey as SupportedChainKey;
  if (key in CHAIN_DESCRIPTORS) {
    return CHAIN_DESCRIPTORS[key];
  }

  // Throw error for unsupported chains - no fallback
  throw new Error(
    `No descriptor available for chain '${chainKey}'. Supported chains: ${Object.keys(CHAIN_DESCRIPTORS).join(', ')}`
  );
}

/**
 * Get typed API for a chain using PAPI v1.14+ pattern
 * @param client - The PAPI client
 * @param chainKey - The chain identifier
 * @returns Typed API with all chain-specific types and methods
 */
export function getTypedApiForChain(client: any, chainKey: string): any {
  const descriptor = getDescriptorForChain(chainKey);
  return client.getTypedApi(descriptor);
}

// Export the descriptors for direct use if needed
export { polkadot, kusama, moonbeam, bifrost, astar, paseo_asset_hub, polkadot_asset_hub, polkadot_people, hydration };
export type { SupportedChainKey };

// List of chains with real descriptors vs unsupported
export const CHAINS_WITH_REAL_DESCRIPTORS = [
  "polkadot",
  "kusama",
  "moonbeam",
  "bifrost",
  "astar",
  "paseo_asset_hub",
  "polkadot_asset_hub",
  "polkadot_people",
  "hydration",
] as const;
export const UNSUPPORTED_CHAINS = ["acala"] as const;
